### ISSUE TITLE
Mimosa configuration readback

### ISSUE THREAD

**Issue by YannickDieter** [SiLab-Bonn/pymosa#13]
Since a few months the readback of the Mimosa26 configuration seems not to work anymore. The chips are configred properly (total current consumption ~ 3.3 A), but the readback of the registers fails.

Is this a sign of chip degration after some time?
It also happens that the chips lose their configuration (current drops down to 1.8 A) out of nothing.

**Comment by DavidLP** [comment]
Chip degradation due to heat? Radiation damage should be negligible... We use the planes without cooling, maybe you can find some experts (at DESY or so) to tell us more.

**Comment by laborleben** [comment]
Maybe a bad power supply, cable, etc.? Before raising the issue, please make sure that you can exclude any other issues that are under our control.

**Comment by YannickDieter** [comment]
@laborleben Yes of course, I opened this issue simply to not forget it. We changed never the power of the Mimosas, and when I started I never observed this problem.

@DavidLP Last time I talked to Andre Rummler and he observed also this problem of losing the configuration. He said that this would be a sign of degradation. But of course, radiation is much harder here at CERN than at ELSA... Cooling could be reason, but I dont know to which temperature the Mimosas will be heaten up during operation without cooling. 

I can ask maybe in the Telescope development meeting someone.

**Comment by DavidLP** [comment]
> But of course, radiation is much harder here at CERN than at ELSA... 

Why is it much harder?

**Comment by YannickDieter** [comment]
Okay radiation is maybe not directly harder, but the telescope here is more in beam than ours at ELSA.

**Comment by laborleben** [comment]
The connectors/plugs/cables/PCBs are under permanent stress when used, e.g., the rigid Ethernet cables tug at the PCBs attached to the Mimosa26 ASICs. Claiming that nothing was changed just doesn't mean it will fail over time.
You mentioned that the configuration is lost after some time, but this can have the origin in a bad cables / connection. Then it is just a matter of time it will fail. That the ASIC is loosing the complete configuration because of radiation damage is very unlikely.

**Comment by DavidLP** [comment]
> That the ASIC is loosing the complete configuration because of radiation damage is very unlikely.

I agree. SEU is unlikely. It is large process and I do not know why SEU should increase over time.

**Comment by YannickDieter** [comment]
> The connectors/plugs/cables/PCBs are under permanent stress when used, e.g., the rigid Ethernet cables tug at the PCBs attached to the Mimosa26 ASICs. Claiming that nothing was changed just doesn't mean it will fail over time.

Yes of course. But we didnt change something obviously. But nevertheless we have this issue, no matter where it comes. And I need to figure out why this is the case..

> You mentioned that the configuration is lost after some time, but this can have the origin in a bad cables / connection.

Okay this is of course the case, because these connector are in general bad and last TB at CERN we had to resolder one connector.. I should solder somehow better/new ones maybe.

**Comment by laborleben** [comment]
This readback issues were solved by this PR https://github.com/SiLab-Bonn/basil/pull/82.

If any problems still exist, please reopen the issue.

**Comment by themperek** [comment]
But SiLab-Bonn/basil#82 should not matter here.

**Comment by laborleben** [comment]
I don't understand. We had issues writing the correct configuration via UDP/JTAG (SiTCP RBCP).

Maybe we have to differentiate between the issues:
1. Readback fails (see https://github.com/SiLab-Bonn/pymosa/blob/27a60117d08dc91a2b03ad697a0ff8609927b07b/pymosa/m26.py#L106). This should be fixed by the PR https://github.com/SiLab-Bonn/basil/pull/82.
2. Sudden current drops/losing the configuration. Not observed with ANEMONE in Bonn. Maybe an issue of the power supply used at CERN.
