### ISSUE TITLE
Do not flush on every readout and use larger chunks

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pymosa#3]
To optimize the write speed during data taking one could not [flush on every readout](https://github.com/SiLab-Bonn/pymosa/blob/72f3829addb2a3d847e5971a96791c9b0c85c3cc/pymosa/m26.py#L353) and use a [predefined chunks size ~ 2e15](https://www.pytables.org/usersguide/optimization.html#fine-tuning-the-chunksize).

**Comment by laborleben** [comment]
This is done!

**Comment by laborleben** [comment]
M26Readout is buffering the the data for x seconds: https://github.com/SiLab-Bonn/pymosa/blob/fdfef811b4a34ad789956a651c8371e0bb80cf59/pymosa/m26_readout.py#L56

The buffering happens in the writer thread: https://github.com/SiLab-Bonn/pymosa/blob/fdfef811b4a34ad789956a651c8371e0bb80cf59/pymosa/m26_readout.py#L350

The callback method is using ```M26RawDataFile .append()``` (instead of ```append_item()```): https://github.com/SiLab-Bonn/pymosa/blob/fdfef811b4a34ad789956a651c8371e0bb80cf59/pymosa/m26_raw_data.py#L211

A flush is of course still set to ```True``` (to prevent from data loss) but flush is called only once.
